# Nombre de la aplicación
spring.application.name=af-crm-server

# Configuración de la Base de Datos usando Variables de Entorno
# Si la variable no existe, fallará (lo cual es bueno para detectar errores de config)
spring.datasource.url=jdbc:postgresql://db:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}

# JPA / Hibernate Properties
# 'update' crea las tablas automáticamente al detectar tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evita que la app intente conectar antes de que la DB esté lista
spring.datasource.hikari.initialization-fail-timeout=0